#' Get Sentinel-2 imagery
#'
#' This function downloads Landsat imagery from a STAC endpoint, by default
#' Microsoft's Planetary Computer. The `sentinel_band_mapping` object included
#' in this package contains metadata relevant to several free STAC endpoints,
#' namely Planetary Computer and AWS's STAC endpoint versions 0 and 1.
#'
#' @param aoi An sf(c) object outlining the area of interest to get imagery for.
#' Will be used to get the bounding box used for calculating metrics and the
#' output data's CRS.
#' @param start_date,end_date Character of length 1: The first and last date,
#' respectively, of imagery to include in metrics calculations. Should be in
#' YYYY-MM-DD format.
#' @param remap_band_names A named vector, with names corresponding to band
#' names in the STAC catalog and values corresponding to the values they should
#' be updated to. Set to `NULL` to not remap band names.
#' @param stac_source Character of length 1: the STAC URL to download
#' imagery from. Defaults to the `stac_source` attribute of `remap_band_names`.
#' @param pixel_x_size Numeric of length 1: size of pixels in x-direction
#' (longitude / easting).
#' @param pixel_y_size Numeric of length 1: size of pixels in y-direction
#' (latitude / northing).
#' @param imagery_time_step Character of length 1: ISO8601 period string (eg
#' "P1D", "P1Y") specifying the time step of imagery to get imagery for
#' (and, if `reduce_time = FALSE`, to save out).
#' @param imagery_aggregation_function Character of length 1: aggregation method
#' used to combine pixels with data from multiple images. Can be "min", "max",
#' "mean", "median", or "first".
#' @param imagery_resampling_function Character of length 1: resampling method
#' used in gdalwarp when images are read, can be "near", "bilinear", "bicubic"
#' or others as supported by gdalwarp.
#' @param reduce_time Logical of length 1: reduce all downloaded images into a
#' single image? Note that it's often more efficient to set `imagery_time_step`
#' to the same amount of time as imagery is being downloaded for.
#' @param scl_band_name Character of length 1: The name of the SCL band in your
#' STAC source. The built-in band mappings (stored in `sentinel_band_mapping`)
#' store this in the `scl_name` attribute of each set, which will be used
#' automatically if this argument is not manually provided.
#' @param download_function A function that takes the output from
#' [rstac::stac_search()] and executes the request. Use this if you need to sign
#' requests for your endpoint, or use a non-GET verb.
#' @inheritParams rstac::stac_search
#' @inheritParams gdalcubes::write_tif
#' @inheritParams gdalcubes::apply_pixel.cube
#' @inheritParams rlang::args_dots_empty
#' @param reduce_function Character of length 1: the function to use to collapse
#' pixel values for each time interval into a single value for the entire
#' period. Possible reducers currently are "min", "max", "sum", "prod", "count",
#' "mean", "median", "var", "sd", "which_min", "which_max", "Q1" (1st quartile),
#' and "Q3" (3rd quartile).
#' @param directory The directory to save files generated by
#' [gdalcubes::write_tif()] into.
#'
#' @examples
#' \dontrun{
#' aoi <- sf::st_point(c(-74.912131, 44.080410)) |>
#'   sf::st_sfc() |>
#'   sf::st_set_crs(4326) |>
#'   sf::st_transform(3857) |>
#'   sf::st_buffer(100)
#'
#' get_sentinel2_imagery(
#'   aoi,
#'   "2022-06-01",
#'   "2022-08-30"
#' )
#'
#' # Or, to use AWS instead...
#' get_sentinel2_imagery(
#'   aoi,
#'   "2022-06-01",
#'   "2022-08-30",
#'   remap_band_names = sentinel_band_mapping$aws_v1
#' )
#' }
#'
#' @returns The file path images were written to.
#'
#' @export
get_sentinel2_imagery <- function(aoi,
                                  start_date,
                                  end_date,
                                  ...,
                                  pixel_x_size = 10,
                                  pixel_y_size = 10,
                                  imagery_time_step = "P1D",
                                  imagery_aggregation_function = "median",
                                  imagery_resampling_function = "bilinear",
                                  reduce_time = TRUE,
                                  remap_band_names = sentinel_band_mapping$planetary_computer_v1,
                                  stac_source = attr(remap_band_names, "stac_source"),
                                  collections = attr(remap_band_names, "collection_name"),
                                  scl_band_name = attr(remap_band_names, "scl_name"),
                                  download_function = attr(remap_band_names, "download_function"),
                                  limit = 999,
                                  creation_options = list(
                                    "COMPRESS" = "DEFLATE",
                                    "PREDICTOR" = "3"
                                  ),
                                  reduce_function = "median",
                                  directory = ".") {
  rlang::check_dots_empty()

  scl_band_name <- scl_band_name %||% "scl"
  # Remove (set to NA) the following values:
  stac_mask <- gdalcubes::image_mask(
    scl_band_name,
    values = c(
      0, # NO_DATA
      1, # SATURATED_OR_DEFECTIVE
      3, # CLOUD_SHADOWS
      8, # CLOUD_MEDIUM_PROBABILITY
      9, # CLOUD_HIGH_PROBABILITY
      10 # THIN_CIRRUS
    )
  )
  # That means we leave in:
  # c(
  #   2, # DARK_AREA_PIXELS
  #   4, # VEGETATION
  #   5, # NOT_VEGETATED
  #   6, # WATER
  #   7, # UNCLASSIFIED
  #   11 # SNOW
  # )
  assets <- c(names(remap_band_names), scl_band_name)

  bbox <- sf::st_bbox(aoi)
  crs <- sf::st_crs(aoi)
  bbox_wgs84 <- sf::st_transform(aoi, 4326) |> sf::st_bbox()

  items <- get_items(
    bbox_wgs84,
    stac_source,
    collections,
    start_date,
    end_date,
    limit,
    download_function
  )

  stac_collection <- make_raster_cube(items$features,
                                      assets = assets,
                                      mask = stac_mask,
                                      wkt = crs$wkt,
                                      pixel_x_size,
                                      pixel_y_size,
                                      imagery_time_step,
                                      imagery_aggregation_function,
                                      imagery_resampling_function,
                                      bbox,
                                      start_date,
                                      end_date
  )

  stac_collection <- remap_reformulate_reduce(
    stac_collection,
    remap_band_names,
    reduce_time,
    reduce_function
  )

  out <- gdalcubes::write_tif(
    stac_collection,
    directory,
    creation_options = creation_options
  )
  out
}
